version: "3.7"

services:
  postgres:
    image: postgres:13.4
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=$name$
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-password
